# by pedram shahsafi <pd.shahsafi@gmail.com>
image: python
stages:
  - build
  - test
  - deploy

before_script:
  - echo "before script running..."

APIProviderTest:
  stage: build
  script:
    - echo "APIProvider build stage is running..."

  stage: test
  script:
    - echo "APIProvider test stage is running..."

  stage: deploy
  script:
     - echo "APIProvider deploy stage is running..."
