# by pedram shahsafi <pd.shahsafi@gmail.com>
image: debian
# services:
#   - docker:dind
stages:
  - build
  - test
  - deploy
before_script:
  - echo "before script running..."
build:
  stage: build
  script:
    - echo "build stage"
test:
  stage: test
  script:
    - echo "testing..."
    - apt update
    - apt upgrade
    - apt add --no-cache python3 py3-pip
    - pip3 install docker-compose
    - docker-compose build
    - docker-compose up -d
    - python3 ./rsplatform/APIProvider/tests/test.py
deploy:
  stage: deploy
  script:
     - echo "APIProvider deploy stage is running..."
     - echo "nothing to do right now..."
