# by pedram shahsafi <pd.shahsafi@gmail.com>
image: docker
services:
  - docker:dind
stages:
  - build
  - test
  - deploy
before_script:
  - echo "before script running..."
  - apk update
  - apk upgrade
  - apk add --no-cache python3 py3-pip
  - pip3 install docker-compose
build:
  stage: build
  script:
    - docker-compose build
    - docker-compose up -d
    - python3 ./rsplatform/APIProvider/tests/auth_test.py
test:
  stage: test
  script:
    - echo "testing..."
deploy:
  stage: deploy
  script:
     - echo "APIProvider deploy stage is running..."
     - echo "nothing to do right now..."
