# by pedram shahsafi <pd.shahsafi@gmail.com>
image: docker

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - echo "before script running..."

build:
  stage: build
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker-compose build
    - docker-compose up -d

test:
  stage: test
  script:
    - echo "testing..."
    - python ./rsplatform/APIProvider/tests/auth_test.py

deploy:
  stage: deploy
  script:
     - echo "APIProvider deploy stage is running..."
     - echo "nothing to do right now..."
