# by pedram shahsafi <pd.shahsafi@gmail.com>
image: debian
# services:
#   - docker:dind
stages:
  - build
  - test
  - deploy
before_script:
  - echo "before script running..."
build:
  stage: build
  script:
    - echo "build stage"
test:
  stage: test
  script:
    - echo "testing..."
    - apt update -y
    - apt upgrade -y
    - apt install -y python3 python3-pip
    - apt install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - apt update -y
    - apt install -y docker-ce
    - usermod -aG docker ${USER}
    - su - ${USER}
    - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - docker-compose --version
    - systemctl status docker
    - systemclt status docker-compose
    - docker-compose build
    - docker-compose up -d
    - python3 ./rsplatform/APIProvider/tests/test.py
deploy:
  stage: deploy
  script:
     - echo "APIProvider deploy stage is running..."
     - echo "nothing to do right now..."
