version: '3'
services:
  database:
    build: rsplatform/mongodb/
    networks:
      - database_bridge
    ports:
      - 27017:27017
  apiprovider:
    build: rsplatform/APIProvider/
    ports:
      - 5000:5000
    networks:
      - database_bridge
    volumes:
      - ./rsplatform:/rsplatform
    depends_on:
      - "nginx"
  nginx:
    build: rsplatform/nginx/
    networks:
      - nginx_bridge
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./rsplatform/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "database"
  react:
    build: rsplatform/interface/
    ports:
      - 3000:3000
    networks:
      - nginx_bridge
    volumes:
      - ./rsplatform/interface/:/rsplatform/interface/
    depends_on:
      - "apiprovider"
networks:
  database_bridge:
    driver: bridge
  nginx_bridge:
    driver: bridge
