version: '3'
services:
  database:
    build: rsplatform/mongodb/
    networks:
      - database_bridge
    ports:
      - 27017:27017
  apiprovider:
    build: rsplatform/APIProvider/
    ports:
      - 5000:5000
    networks:
      - database_bridge
    volumes:
      - './rsplatform:/rsplatform'
networks:
  database_bridge:
    driver: bridge
